apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding
  namespace: lmw-fitness
spec:
  params:
    - name: GIT_REVISION
      value: $(body.head_commit.id)
    - name: GITHUB_CLONE_URL
      value: $(body.repository.clone_url)
    - name: IMAGE
      value: "index.docker.io/lmwcode/$(body.repository.name):$(body.head_commit.id)"
    - name: DOCKERFILE
      value: Dockerfile
    - name: CONTEXT
      value: "."
    - name: EXTRA_ARGS
      value: "--cache=false"
    - name: BUILDER_IMAGE
      value: "gcr.io/kaniko-project/executor:v1.5.1@sha256:c6166717f7fe0b7da44908c986137ecfeab21f31ec3992f6e128fff8a94be8a5"