apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-deploy
  namespace: lmw-fitness
spec:
  params:
  - name: RELEASE_NAME
    type: string
    description: Name of the Helm release
  - name: HELM_FILE
    type: string
    description: Path containing the Helm chart
  - name: NAMESPACE
    type: string
    description: Kubernetes namespace for the release
  - name: VALUES_MANIFEST_PATH
    type: string
    description: Path to the values manifest file
  steps:
  - name: list-files
    image: alpine
    workingDir: $(workspaces.helm-chart.path)
    script: |
      #!/bin/sh
      echo "Listing contents of $(workspaces.helm-chart.path):"
      ls -lah
  - name: helm-deploy
    image: alpine/helm:3.14.0
    workingDir: $(workspaces.helm-chart.path)
    script: |
        #!/bin/sh
        set -e
        helm upgrade --install $(params.RELEASE_NAME) \
        $(workspaces.helm-chart.path)/$(params.HELM_FILE) \
        --namespace $(params.NAMESPACE) \
        --create-namespace \
        --values $(workspaces.helm-chart.path)/$(params.VALUES_MANIFEST_PATH) \
        --wait 
  workspaces:
  - name: helm-chart