apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template
  namespace: lmw-fitness
spec:
  params:
  - name: GITHUB_CLONE_URL
  - name: GITHUB_HELM_URL
  - name: IMAGE
  - name: DOCKERFILE
  - name: CONTEXT
  - name: EXTRA_ARGS
  - name: BUILDER_IMAGE
  - name: VALUES_MANIFEST_PATH
  - name: SERVICE_TYPE
  - name: HELM_FILE
  # - name: RELEASE_NAME
  # - name: NAMESPACE
  - name: COMMIT_MESSAGE
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: build-test-deploy-pipeline-run-
      namespace: lmw-fitness
    spec:
      pipelineRef:
        name: build-test-deploy-pipeline
      params:
      - name: GITHUB_CLONE_URL
        value: $(tt.params.GITHUB_CLONE_URL)
      - name: GITHUB_HELM_URL
        value: $(tt.params.GITHUB_HELM_URL)
      - name: IMAGE
        value: $(tt.params.IMAGE)
      - name: DOCKERFILE
        value: $(tt.params.DOCKERFILE)
      - name: CONTEXT
        value: $(tt.params.CONTEXT)
      - name: EXTRA_ARGS
        value: $(tt.params.EXTRA_ARGS)
      - name: BUILDER_IMAGE
        value: $(tt.params.BUILDER_IMAGE)
      - name: VALUES_MANIFEST_PATH
        value: $(tt.params.VALUES_MANIFEST_PATH)
      - name: SERVICE_TYPE
        value: $(tt.params.SERVICE_TYPE)
      - name: HELM_FILE
        value: $(tt.params.HELM_FILE)
      # - name: RELEASE_NAME
      #   value: $(tt.params.RELEASE_NAME)
      # - name: NAMESPACE
      #   value: $(tt.params.NAMESPACE)
      - name: COMMIT_MESSAGE
      workspaces:
        - name: source
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - name: helm-chart
          volumeClaimTemplate:
            metadata:
              creationTimestamp: null
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - name: git-credentials
          secret:
            secretName: git-credentials
        - name: docker-config
          secret:
            secretName: docker-config