apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding
  namespace: lmw-fitness
spec:
  params:
    - name: GITHUB_CLONE_URL
      value: $(body.repository.clone_url)
    # - name: SONAR_HOST_URL
    #   value: "https://sonarqube.lmwfitness.com"
    # - name: PROJECT_KEY
    #   value: "$(body.repository.name)-$(body.after)"
    - name: GITHUB_HELM_URL
      value: "https://github.com/88Warren/lmw-fitness-helmchart.git"
    - name: IMAGE
      value: "index.docker.io/lmwcode/$(body.repository.name):$(body.after)"
    - name: DOCKERFILE
      value: Dockerfile
    - name: CONTEXT
      value: "."
    - name: BUILDER_IMAGE
      value: "gcr.io/kaniko-project/executor:v1.5.1@sha256:c6166717f7fe0b7da44908c986137ecfeab21f31ec3992f6e128fff8a94be8a5"
    - name: TRIVY_SEVERITY
      value: "CRITICAL,HIGH"
    - name: VALUES_MANIFEST_PATH
      value: "$(body.repository.description)/values.yaml"
    - name: SERVICE_TYPE
      value: $(body.repository.description)
    - name: HELM_FILE
      value: "$(body.repository.description)/"
    - name: COMMIT_MESSAGE
      value: "Update image in Helm chart"